# Configuração do Banco de Dados
db.url=jdbc:mysql://mysql-33817aa2-deliverycartuchoss-97c4.g.aivencloud.com:20897/defaultdb?useSSL=true&allowPublicKeyRetrieval=true
db.user=avnadmin
db.password=AVNS_GoSr6Fxq7_eDGNpY7Cp
